export const genderOptions = [
  { id: 1, label: "Man", value: "man" },
  { id: 2, label: "Woman", value: "woman" },
  { id: 3, label: "Other", value: "other" },
];

export const hobbyOptions = [
  { id: 1, label: "Reading", value: "reading" },
  { id: 2, label: "Drawing", value: "drawing" },
  { id: 3, label: "Cooking", value: "cooking" },
  { id: 4, label: "Photography", value: "photography" },
  { id: 5, label: "Gardening", value: "gardening" },
  { id: 6, label: "Playing an Instrument", value: "playing_instrument" },
  { id: 7, label: "Writing", value: "writing" },
  { id: 8, label: "Dancing", value: "dancing" },
  { id: 9, label: "Hiking", value: "hiking" },
  { id: 10, label: "Sports", value: "sports" },
  { id: 11, label: "Painting", value: "painting" },
  { id: 12, label: "Sculpting", value: "sculpting" },
  { id: 13, label: "Woodworking", value: "woodworking" },
  { id: 14, label: "Model Building", value: "model_building" },
  { id: 15, label: "Camping", value: "camping" },
  { id: 16, label: "Fishing", value: "fishing" },
  { id: 17, label: "Gaming", value: "gaming" },
  { id: 18, label: "Knitting", value: "knitting" },
  { id: 19, label: "Crocheting", value: "crocheting" },
  { id: 20, label: "Sewing", value: "sewing" },
  { id: 21, label: "Calligraphy", value: "calligraphy" },
  { id: 22, label: "Origami", value: "origami" },
  { id: 23, label: "Cycling", value: "cycling" },
  { id: 24, label: "Running", value: "running" },
  { id: 25, label: "Swimming", value: "swimming" },
  { id: 26, label: "Surfing", value: "surfing" },
  { id: 27, label: "Bird Watching", value: "bird_watching" },
  { id: 28, label: "Collecting Stamps", value: "collecting_stamps" },
  { id: 29, label: "Collecting Coins", value: "collecting_coins" },
  { id: 30, label: "Collecting Postcards", value: "collecting_postcards" },
  { id: 31, label: "Wine Tasting", value: "wine_tasting" },
  { id: 32, label: "Beer Brewing", value: "beer_brewing" },
  { id: 33, label: "Baking", value: "baking" },
  { id: 34, label: "Wine Making", value: "wine_making" },
  { id: 35, label: "Beer Tasting", value: "beer_tasting" },
  { id: 36, label: "Film Making", value: "film_making" },
  { id: 37, label: "Podcasting", value: "podcasting" },
  { id: 38, label: "Vlogging", value: "vlogging" },
  { id: 39, label: "Yoga", value: "yoga" },
  { id: 40, label: "Scrapbooking", value: "scrapbooking" },
  { id: 41, label: "Chess", value: "chess" },
  { id: 42, label: "Singing", value: "singing" },
  { id: 43, label: "Pottery", value: "pottery" },
  { id: 44, label: "Meditation", value: "meditation" },
  { id: 45, label: "Rock Climbing", value: "rock_climbing" },
  { id: 46, label: "Skiing", value: "skiing" },
  { id: 47, label: "Snowboarding", value: "snowboarding" },
  { id: 48, label: "Traveling", value: "traveling" },
  { id: 49, label: "Jewelry Making", value: "jewelry_making" },
  { id: 50, label: "Astrology", value: "astrology" },
  { id: 51, label: "Horseback Riding", value: "horseback_riding" },
  { id: 52, label: "Beekeeping", value: "beekeeping" },
  { id: 53, label: "Golfing", value: "golfing" },
  { id: 54, label: "Photography", value: "photography" },
  { id: 55, label: "Collecting Records", value: "collecting_records" },
  { id: 56, label: "Urban Exploration", value: "urban_exploration" },
  { id: 57, label: "Archery", value: "archery" },
  { id: 58, label: "Amateur Radio", value: "amateur_radio" },
  { id: 59, label: "Cooking", value: "cooking" },
  { id: 60, label: "Biking", value: "biking" },
];

export const fishingOptions = [
  { id: 1, label: "Spinning fishing", value: "spinning-fishing" },
  { id: 2, label: "Feeder fishing", value: "feeder-fishing" },
  { id: 3, label: "Fly fishing", value: "fly-fishing" },
  { id: 4, label: "Carp fishing", value: "carp-fishing" },
  { id: 5, label: "Catfish fishing", value: "catfish-fishing" },
  { id: 6, label: "Live bait fishing", value: "live-bait-fishing" },
  { id: 7, label: "Ice jig fishing", value: "ice-jig-fishing" },
  { id: 8, label: "Spoon fishing", value: "spoon-fishing" },
  { id: 9, label: "Sea spinning fishing", value: "sea-spinning-fishing" },
  { id: 10, label: "Freshwater fly fishing", value: "freshwater-fly-fishing" },
  { id: 11, label: "Ice fishing", value: "ice-fishing" },
  { id: 12, label: "Sport fishing", value: "sport-fishing" },
  { id: 13, label: "Trolling", value: "trolling" },
  { id: 14, label: "Float fishing", value: "float-fishing" },
  { id: 15, label: "Jigging rod fishing", value: "jigging-rod-fishing" },
];
